// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestTaskApi.Infrastructure.Data;

#nullable disable

namespace TestTaskApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260914180558_InitialCreate.")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookingUtility", b =>
                {
                    b.Property<int>("BookingsId")
                        .HasColumnType("integer");

                    b.Property<int>("UtilitiesId")
                        .HasColumnType("integer");

                    b.HasKey("BookingsId", "UtilitiesId");

                    b.HasIndex("UtilitiesId");

                    b.ToTable("BookingUtility");
                });

            modelBuilder.Entity("RoomUtility", b =>
                {
                    b.Property<int>("RoomsId")
                        .HasColumnType("integer");

                    b.Property<int>("UtilitiesId")
                        .HasColumnType("integer");

                    b.HasKey("RoomsId", "UtilitiesId");

                    b.HasIndex("UtilitiesId");

                    b.ToTable("RoomUtility");
                });

            modelBuilder.Entity("TestTaskApi.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TestTaskApi.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePricePerHour")
                        .HasColumnType("numeric");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePricePerHour = 2000m,
                            Capacity = 50,
                            Name = "Room A"
                        },
                        new
                        {
                            Id = 2,
                            BasePricePerHour = 3500m,
                            Capacity = 100,
                            Name = "Room B"
                        },
                        new
                        {
                            Id = 3,
                            BasePricePerHour = 1500m,
                            Capacity = 30,
                            Name = "Room C"
                        });
                });

            modelBuilder.Entity("TestTaskApi.Domain.Entities.Utility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Utilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 500m,
                            Name = "Projector"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 300m,
                            Name = "Wi-Fi"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 700m,
                            Name = "Sound"
                        });
                });

            modelBuilder.Entity("BookingUtility", b =>
                {
                    b.HasOne("TestTaskApi.Domain.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestTaskApi.Domain.Entities.Utility", null)
                        .WithMany()
                        .HasForeignKey("UtilitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoomUtility", b =>
                {
                    b.HasOne("TestTaskApi.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestTaskApi.Domain.Entities.Utility", null)
                        .WithMany()
                        .HasForeignKey("UtilitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestTaskApi.Domain.Entities.Booking", b =>
                {
                    b.HasOne("TestTaskApi.Domain.Entities.Booking", null)
                        .WithMany("Bookings")
                        .HasForeignKey("BookingId");

                    b.HasOne("TestTaskApi.Domain.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("TestTaskApi.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("TestTaskApi.Domain.Entities.Room", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
